{% set name = "pygacode" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f1ac80b6377bc37a9184187295eeff54a0d61501e394946d1ba064cd5a18b27
  patches:
    - 0001-changing.patch  # [linux]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<=36 or win or linux32 or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('fortran') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    - pip
    - python
    - numpy >=1.18
    - libgomp      # [linux]
    - llvm-openmp  # [osx]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - scikit-image >=0.13

about:
  home: https://gacode.io/
  license: MIT
  license_family: MIT
  license_file: PKG-INFO
  summary: Python interface to gacode profile and geometry tools.
  doc_url: https://gacode.io/

extra:
  recipe-maintainers:
    - kalling
    - smithsp
    - orso82
