{% set name = "pygacode" %}
{% set version = "0.53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fda50ce6c794e4b71851ad1b5e48475c4e0a57f6dc6b5ad990d117a92403888
  patches:
    - 0001-changing.patch  # [linux]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py27 or win or not x86_64]

requirements:
  build:
    - {{ compiler('fortran') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    - pip
    - python
    - numpy >=1.18
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]

about:
  home: https://gacode.io/
  license: MIT
  license_family: MIT
  license_file: PKG-INFO
  summary: Python interface to gacode profile and geometry tools.
  doc_url: https://gacode.io/

extra:
  recipe-maintainers:
    - kalling
    - smithsp
    - orso82
